CPP_ARGS=-m32

all: tails-clone-persistent-helper

tails-clone-persistent-helper: tails-clone-persistent-helper.cpp
	g++ $CPP_ARGS tails-clone-persistent-helper.cpp -o tails-clone-persistent-helper

clean:
	rm tails-clone-persistent-helper

